const fs = require('fs');
const path = require('path');

const targetPath = path.join(__dirname, '../data/lessons/n5-lesson4.json');
let lessonData = JSON.parse(fs.readFileSync(targetPath, 'utf8'));

const newVocabulary = [
  { id: "v1", word: "北", kanji: "北", hiragana: "きた", reading: "kita", meaning: "Phía bắc" },
  { id: "v2", word: "南", kanji: "南", hiragana: "みなみ", reading: "minami", meaning: "Phía nam" },
  { id: "v3", word: "東", kanji: "東", hiragana: "ひがし", reading: "higashi", meaning: "Phía đông" },
  { id: "v4", word: "西", kanji: "西", hiragana: "にし", reading: "nishi", meaning: "Phía tây" },
  { id: "v5", word: "真ん中", kanji: "真ん中", hiragana: "まんなか", reading: "mannaka", meaning: "Chính giữa" },
  { id: "v6", word: "車", kanji: "車", hiragana: "くるま", reading: "kuruma", meaning: "Ô tô" },
  { id: "v7", word: "新幹線", kanji: "新幹線", hiragana: "しんかんせん", reading: "shinkansen", meaning: "Tàu cao tốc Shinkansen" },
  { id: "v8", word: "電車", kanji: "電車", hiragana: "でんしゃ", reading: "densha", meaning: "Tàu điện" },
  { id: "v9", word: "飛行機", kanji: "飛行機", hiragana: "ひこうき", reading: "hikouki", meaning: "Máy bay" },
  { id: "v10", word: "駅", kanji: "駅", hiragana: "えき", reading: "eki", meaning: "Nhà ga" },
  { id: "v11", word: "町", kanji: "町", hiragana: "まち", reading: "machi", meaning: "Thành phố, thị trấn" },
  { id: "v12", word: "時間", kanji: "時間", hiragana: "じかん", reading: "jikan", meaning: "Tiếng (khoảng thời gian)" },
  { id: "v13", word: "時間半", kanji: "時間半", hiragana: "じかんはん", reading: "jikanhan", meaning: "Tiếng rưỡi" },
  { id: "v14", word: "分", kanji: "分", hiragana: "ふん", reading: "fun/pun", meaning: "Phút" },
  { id: "v15", word: "歩いて", kanji: "歩いて", hiragana: "あるいて", reading: "aruite", meaning: "Đi bộ" },
  { id: "v16", word: "くらい", hiragana: "くらい", reading: "kurai", meaning: "Khoảng" },
  { id: "v17", word: "どのくらい", hiragana: "どのくらい", reading: "donokurai", meaning: "Bao lâu" },
  { id: "v18", word: "温泉", kanji: "温泉", hiragana: "おんせん", reading: "onsen", meaning: "Suối nước nóng" },
  { id: "v19", word: "川", kanji: "川", hiragana: "かわ", reading: "kawa", meaning: "Sông" },
  { id: "v20", word: "山", kanji: "山", hiragana: "やま", reading: "yama", meaning: "Núi" },
  { id: "v21", word: "教会", kanji: "教会", hiragana: "きょうかい", reading: "kyoukai", meaning: "Nhà thờ" },
  { id: "v22", word: "お城", kanji: "お城", hiragana: "おしろ", reading: "oshiro", meaning: "Lâu đài" },
  { id: "v23", word: "神社", kanji: "神社", hiragana: "じんじゃ", reading: "jinja", meaning: "Đền" },
  { id: "v24", word: "お寺", kanji: "お寺", hiragana: "おてら", reading: "otera", meaning: "Chùa" },
  { id: "v25", word: "ビル", hiragana: "ビル", reading: "biru", meaning: "Tòa nhà" },
  { id: "v26", word: "ところ", hiragana: "ところ", reading: "tokoro", meaning: "Nơi, chỗ" },
  { id: "v27", word: "人", kanji: "人", hiragana: "ひと", reading: "hito", meaning: "Người" },
  { id: "v28", word: "緑", kanji: "緑", hiragana: "みどり", reading: "midori", meaning: "Màu xanh; Cây xanh" },
  { id: "v29", word: "あります", kanji: "あります", hiragana: "あります", reading: "arimasu", meaning: "Có (đồ vật, địa điểm)" },
  { id: "v30", word: "新しい", kanji: "新しい", hiragana: "あたらしい", reading: "atarashii", meaning: "Mới" },
  { id: "v31", word: "古い", kanji: "古い", hiragana: "ふるい", reading: "furui", meaning: "Cũ" },
  { id: "v32", word: "いい", hiragana: "いい", reading: "ii", meaning: "Tốt" },
  { id: "v33", word: "多い", kanji: "多い", hiragana: "おおい", reading: "ooi", meaning: "Nhiều ～" },
  { id: "v34", word: "少ない", kanji: "少ない", hiragana: "すくない", reading: "sukunai", meaning: "Ít ～" },
  { id: "v35", word: "大きい", kanji: "大きい", hiragana: "おおきい", reading: "ookii", meaning: "To, lớn" },
  { id: "v36", word: "小さい", kanji: "小さい", hiragana: "ちいさい", reading: "chiisai", meaning: "Nhỏ, bé" },
  { id: "v37", word: "高い", kanji: "高い", hiragana: "たかい", reading: "takai", meaning: "Cao, đắt" },
  { id: "v38", word: "低い", kanji: "低い", hiragana: "ひくい", reading: "hikui", meaning: "Thấp" },
  { id: "v39", word: "きれい", hiragana: "きれい", reading: "kirei", meaning: "Đẹp, sạch sẽ" },
  { id: "v40", word: "静か", kanji: "静か", hiragana: "しずか", reading: "shizuka", meaning: "Yên tĩnh" },
  { id: "v41", word: "にぎやか", hiragana: "にぎやか", reading: "nigiyaka", meaning: "Náo nhiệt, nhộn nhịp" },
  { id: "v42", word: "有名", kanji: "有名", hiragana: "ゆうめい", reading: "yuumei", meaning: "Nổi tiếng" },
  { id: "v43", word: "どんな", hiragana: "どんな", reading: "donna", meaning: "Như thế nào" },
  { id: "v44", word: "そして", hiragana: "そして", reading: "soshite", meaning: "Và" },
  { id: "v45", word: "雨", kanji: "雨", hiragana: "あめ", reading: "ame", meaning: "Mưa" },
  { id: "v46", word: "雪", kanji: "雪", hiragana: "ゆき", reading: "yuki", meaning: "Tuyết" },
  { id: "v47", word: "日", kanji: "日", hiragana: "ひ", reading: "hi", meaning: "Ngày / Mặt trời" },
  { id: "v48", word: "メロン", hiragana: "メロン", reading: "meron", meaning: "Dưa gang (dưa lưới)" },
  { id: "v49", word: "暖かい", kanji: "暖かい", hiragana: "あたたかい", reading: "atatakai", meaning: "Ấm áp (thời tiết)" },
  { id: "v50", word: "涼しい", kanji: "涼しい", hiragana: "すずしい", reading: "suzushii", meaning: "Mát mẻ" },
  { id: "v51", word: "暑い", kanji: "暑い", hiragana: "あつい", reading: "atsui", meaning: "Nóng bức (thời tiết)" },
  { id: "v52", word: "寒い", kanji: "寒い", hiragana: "さむい", reading: "samui", meaning: "Lạnh, rét (thời tiết)" },
  { id: "v53", word: "天気がいい", kanji: "天気がいい", hiragana: "てんきがいい", reading: "tenkigaii", meaning: "Thời tiết đẹp" },
  { id: "v54", word: "天気がわるい", kanji: "天気がわるい", hiragana: "てんきがわるい", reading: "tenkigawarui", meaning: "Thời tiết xấu" },
  { id: "v55", word: "温かい", kanji: "温かい", hiragana: "あたたかい", reading: "atatakai", meaning: "Ấm (nhiệt độ, cảm giác)" },
  { id: "v56", word: "熱い", kanji: "熱い", hiragana: "あつい", reading: "atsui", meaning: "Nóng (nhiệt độ)" },
  { id: "v57", word: "冷たい", kanji: "冷たい", hiragana: "つめたい", reading: "tsumetai", meaning: "Lạnh / Mát (nhiệt độ, cảm giác)" },
  { id: "v58", word: "おいしい", hiragana: "おいしい", reading: "oishii", meaning: "Ngon" },
  { id: "v59", word: "甘い", kanji: "甘い", hiragana: "あまい", reading: "amai", meaning: "Ngọt" },
  { id: "v60", word: "辛い", kanji: "辛い", hiragana: "からい", reading: "karai", meaning: "Cay" },
  { id: "v61", word: "苦い", kanji: "苦い", hiragana: "にがい", reading: "nigai", meaning: "Đắng" },
  { id: "v62", word: "すっぱい", hiragana: "すっぱい", reading: "suppai", meaning: "Chua" },
  { id: "v63", word: "一年中", kanji: "一年中", hiragana: "いちねんじゅう", reading: "ichinenjuu", meaning: "Suốt 1 năm" },
  { id: "v64", word: "あまり", hiragana: "あまり", reading: "amari", meaning: "Không ～ lắm" },
  { id: "v65", word: "少し", kanji: "少し", hiragana: "すこし", reading: "sukoshi", meaning: "Một chút, ít" },
  { id: "v66", word: "とても", hiragana: "とても", reading: "totemo", meaning: "Rất" },
  { id: "v67", word: "どう", hiragana: "どう", reading: "dou", meaning: "Thế nào" },
  { id: "v68", word: "そうですね", hiragana: "そうですね", reading: "soudesune", meaning: "Đồng tình với ý kiến người khác" },
  { id: "v69", word: "タクシー", hiragana: "タクシー", reading: "takushii", meaning: "Xe taxi" },
  { id: "v70", word: "バイク", hiragana: "バイク", reading: "baiku", meaning: "Xe máy" }
];

lessonData.vocabulary = newVocabulary;

fs.writeFileSync(targetPath, JSON.stringify(lessonData, null, 2), 'utf8');
console.log('Successfully updated vocabulary for n5-lesson4.json');
